const config = require("../../Credentials/Color")
module.exports = {
    name: "colorrole",
    run: async(client, interaction, container) => {
  const member = await interaction.message.guild.members.fetch({
    user: interaction.user.id,
    force: true 
  })
  if(interaction.values[0] == 'Black') {
      if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Black)
        interaction.reply({ content: `We Give <@&${config.ID.Black}> For You`, ephemeral: true })
    }
      
    if(interaction.values[0] == 'White') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.White)
        interaction.reply({ content: `We Give <@&${config.ID.White}> For You`, ephemeral: true })
    }
    if(interaction.values[0] == 'Gray') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Gray)
        interaction.reply({ content: `We Give <@&${config.ID.Gray}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Darkblue') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Darkblue)
        interaction.reply({ content: `We Give <@&${config.ID.Darkblue}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Blue') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Blue)
        interaction.reply({ content: `We Give <@&${config.ID.Blue}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Sky') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Sky)
        interaction.reply({ content: `We Give <@&${config.ID.Sky}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Darkgreen') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Darkgreen)
        interaction.reply({ content: `We Give <@&${config.ID.Darkgreen}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Green') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Green)
        Embed.setDescription(`We Give <@&${config.ID.Green}> For You`)
        interaction.reply({ content: `We Give <@&${config.ID.Green}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Palegreen') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Palegreen)
        interaction.reply({ content: `We Give <@&${config.ID.Palegreen}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Lemon') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Lemon)
        interaction.reply({ content: `We Give <@&${config.ID.Lemon}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Yellow') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Yellow)
        interaction.reply({ content: `We Give <@&${config.ID.Yellow}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Golden') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Golden)
        interaction.reply({ content: `We Give <@&${config.ID.Golden}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Orange') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Orange)
        interaction.reply({ content: `We Give <@&${config.ID.Orange}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Darkorange') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Darkorange)
        interaction.reply({ content: `We Give <@&${config.ID.Darkorange}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Red') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Red)
        interaction.reply({ content: `We Give <@&${config.ID.Red}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Darkred') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Darkred)
        interaction.reply({ content: `We Give <@&${config.ID.Darkred}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Darkpink') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Darkpink)
        interaction.reply({ content: `We Give <@&${config.ID.Darkpink}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Pink') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Pink)
        interaction.reply({ content: `We Give <@&${config.ID.Pink}> For You`, ephemeral: true })
    }

    if(interaction.values[0] == 'Palepink') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Palepink)
        interaction.reply({ content: `We Give <@&${config.ID.Palepink}> For You`, ephemeral: true })
    }
    if(interaction.values[0] == 'PalePurple') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.PalePurple)
        interaction.reply({ content: `We Give <@&${config.ID.PalePurple}> For You`, ephemeral: true })
    }
    if(interaction.values[0] == 'Purple') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Purple)
        interaction.reply({ content: `We Give <@&${config.ID.Purple}> For You`, ephemeral: true })
    }
    if(interaction.values[0] == 'Boldpurple') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        await interaction.member.roles.add(config.ID.Boldpurple)
        interaction.reply({ content: `We Give <@&${config.ID.Boldpurple}> For You`, ephemeral: true })
    }
      if(interaction.values[0] == 'removec') {
        if(interaction.member.roles.cache.has(config.ID.Black))await interaction.member.roles.remove(config.ID.Black)
        if(interaction.member.roles.cache.has(config.ID.Gray))await interaction.member.roles.remove(config.ID.Gray)
        if(interaction.member.roles.cache.has(config.ID.White))await interaction.member.roles.remove(config.ID.White)
        if(interaction.member.roles.cache.has(config.ID.Darkblue))await interaction.member.roles.remove(config.ID.Darkblue)
        if(interaction.member.roles.cache.has(config.ID.Blue))await interaction.member.roles.remove(config.ID.Blue)
        if(interaction.member.roles.cache.has(config.ID.Sky))await interaction.member.roles.remove(config.ID.Sky)
        if(interaction.member.roles.cache.has(config.ID.Darkgreen))await interaction.member.roles.remove(config.ID.Darkgreen)
        if(interaction.member.roles.cache.has(config.ID.Green))await interaction.member.roles.remove(config.ID.Green)
        if(interaction.member.roles.cache.has(config.ID.Palegreen))await interaction.member.roles.remove(config.ID.Palegreen)
        if(interaction.member.roles.cache.has(config.ID.Lemon))await interaction.member.roles.remove(config.ID.Lemon)
        if(interaction.member.roles.cache.has(config.ID.Yellow))await interaction.member.roles.remove(config.ID.Yellow)
        if(interaction.member.roles.cache.has(config.ID.Golden))await interaction.member.roles.remove(config.ID.Golden)
        if(interaction.member.roles.cache.has(config.ID.Orange))await interaction.member.roles.remove(config.ID.Orange)
        if(interaction.member.roles.cache.has(config.ID.Darkorange))await interaction.member.roles.remove(config.ID.Darkorange)
        if(interaction.member.roles.cache.has(config.ID.Red))await interaction.member.roles.remove(config.ID.Red)
        if(interaction.member.roles.cache.has(config.ID.Darkred))await interaction.member.roles.remove(config.ID.Darkred)
        if(interaction.member.roles.cache.has(config.ID.Darkpink))await interaction.member.roles.remove(config.ID.Darkpink)
        if(interaction.member.roles.cache.has(config.ID.Pink))await interaction.member.roles.remove(config.ID.Pink)
        if(interaction.member.roles.cache.has(config.ID.Palepink))await interaction.member.roles.remove(config.ID.Palepink)
        if(interaction.member.roles.cache.has(config.ID.PalePurple))await interaction.member.roles.remove(config.ID.PalePurple)
        if(interaction.member.roles.cache.has(config.ID.Purple))await interaction.member.roles.remove(config.ID.Purple)
        if(interaction.member.roles.cache.has(config.ID.Boldpurple))await interaction.member.roles.remove(config.ID.Boldpurple)
        interaction.reply({ content: `We Remove Color For You`, ephemeral: true })
      }
}
}
